apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: orders-mongo-mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: mongodb
status:
  loadBalancer: {}
